// countryMapping.js
const currencyMapping = {
    Australia: "AUD",
    "United States": "USD",
    "United Kingdom": "GBP",
    Canada: "CAD",
    China: "CNY",
    "United Arab Emirates": "AED",
    Albania: "ALL",
    Armenia: "AMD",
    "Netherlands Antilles": "ANG",
    Angola: "AOA",
    Argentina: "ARS",
    Austria: "EUR",
    Aruba: "AWG",
    Azerbaijan: "AZN",
    "Bosnia and Herzegovina": "BAM",
    Barbados: "BBD",
    Bangladesh: "BDT",
    Bulgaria: "BGN",
    Bahrain: "BHD",
    Bermuda: "BMD",
    Brunei: "BND",
    Bolivia: "BOB",
    Brazil: "BRL",
    Bahamas: "BSD",
    Botswana: "BWP",
    Belarus: "BYN",
    Belize: "BZD",
    Switzerland: "CHF",
    Chile: "CLP",
    Colombia: "COP",
    "Costa Rica": "CRC",
    Cuba: "CUP",
    "Cape Verde": "CVE",
    "Czech Republic": "CZK",
    Djibouti: "DJF",
    Denmark: "DKK",
    "Dominican Republic": "DOP",
    Algeria: "DZD",
    Egypt: "EGP",
    Ethiopia: "ETB",
    Euro: "EUR",
    Fiji: "FJD",
    "Falkland Islands": "FKP",
    "British Pound Sterling": "GBP",
    Georgia: "GEL",
    Gibraltar: "GIP",
    Gambia: "GMD",
    Guinea: "GNF",
    Guatemala: "GTQ",
    Guyana: "GYD",
    "Hong Kong": "HKD",
    Honduras: "HNL",
    Croatia: "HRK",
    Haiti: "HTG",
    Hungary: "HUF",
    Indonesia: "IDR",
    Israel: "ILS",
    India: "INR",
    Iceland: "ISK",
    Jamaica: "JMD",
    Jordan: "JOD",
    Japan: "JPY",
    Kenya: "KES",
    Kyrgyzstan: "KGS",
    Cambodia: "KHR",
    Comoros: "KMF",
    "South Korean Won": "KRW",
    Kuwait: "KWD",
    "Cayman Islands": "KYD",
    Kazakhstan: "KZT",
    Laos: "LAK",
    Lebanon: "LBP",
    "Sri Lanka": "LKR",
    Libya: "LYD",
    Morocco: "MAD",
    Moldova: "MDL",
    Macedonia: "MKD",
    Myanmar: "MMK",
    Mongolia: "MNT",
    Macao: "MOP",
    Mauritania: "MRU",
    Mauritius: "MUR",
    Maldives: "MVR",
    Malawi: "MWK",
    Mexico: "MXN",
    Malaysia: "MYR",
    Mozambique: "MZN",
    Namibia: "NAD",
    Nigeria: "NGN",
    Nicaragua: "NIO",
    Norway: "NOK",
    Nepal: "NPR",
    "New Zealand": "NZD",
    Oman: "OMR",
    Panama: "PAB",
    Peru: "PEN",
    "Papua New Guinea": "PGK",
    Philippines: "PHP",
    Pakistan: "PKR",
    Poland: "PLN",
    Paraguay: "PYG",
    Qatar: "QAR",
    Romania: "RON",
    Serbia: "RSD",
    Russia: "RUB",
    Rwanda: "RWF",
    "Saudi Arabia": "SAR",
    "Solomon Islands": "SBD",
    Seychelles: "SCR",
    Sweden: "SEK",
    Singapore: "SGD",
    "Saint Helena": "SHP",
    "Sierra Leone": "SLL",
    Suriname: "SRD",
    "Sao Tome and Principe": "STN",
    "El Salvador": "SVC",
    Swaziland: "SZL",
    Thailand: "THB",
    Tunisia: "TND",
    Turkey: "TRY",
    "Trinidad and Tobago": "TTD",
    Taiwan: "TWD",
    Tanzania: "TZS",
    Ukraine: "UAH",
    Uganda: "UGX",
    "United States Dollar": "USD",
    Uzbekistan: "UZS",
    Venezuela: "VEF",
    Vietnam: "VND",
    Vanuatu: "VUV",
    Samoa: "WST",
    "CFA Franc BEAC": "XAF",
    "East Caribbean Dollar": "XCD",
    "CFA Franc BCEAO": "XOF",
    "CFP Franc": "XPF",
    Yemen: "YER",
    "South African Rand": "ZAR",
    Zambia: "ZMW",
};
export const countryMapping = {
    Afghanistan: 'AF',
    'Åland Islands': 'AX',
    Albania: 'AL',
    Algeria: 'DZ',
    'American Samoa': 'AS',
    Andorra: 'AD',
    Angola: 'AO',
    Anguilla: 'AI',
    Antarctica: 'AQ',
    'Antigua and Barbuda': 'AG',
    Argentina: 'AR',
    Armenia: 'AM',
    Aruba: 'AW',
    Australia: 'AU',
    Austria: 'AT',
    Azerbaijan: 'AZ',
    Bahamas: 'BS',
    Bahrain: 'BH',
    Bangladesh: 'BD',
    Barbados: 'BB',
    Belarus: 'BY',
    Belgium: 'BE',
    Belize: 'BZ',
    Benin: 'BJ',
    Bermuda: 'BM',
    Bhutan: 'BT',
    'Bolivia (Plurinational State of)': 'BO',
    'Bosnia and Herzegovina': 'BA',
    Botswana: 'BW',
    'Bouvet Island': 'BV',
    Brazil: 'BR',
    'British Indian Ocean Territory': 'IO',
    'Brunei Darussalam': 'BN',
    Bulgaria: 'BG',
    'Burkina Faso': 'BF',
    Burundi: 'BI',
    'Cabo Verde': 'CV',
    Cambodia: 'KH',
    Cameroon: 'CM',
    Canada: 'CA',
    'Cayman Islands': 'KY',
    'Central African Republic': 'CF',
    Chad: 'TD',
    Chile: 'CL',
    China: 'CN',
    'Christmas Island': 'CX',
    'Cocos (Keeling) Islands': 'CC',
    Colombia: 'CO',
    Comoros: 'KM',
    Congo: 'CG',
    'Congo (Democratic Republic of the)': 'CD',
    'Cook Islands': 'CK',
    'Costa Rica': 'CR',
    'Côte d\'Ivoire': 'CI',
    Croatia: 'HR',
    Curaçao: 'CW',
    Cyprus: 'CY',
    Czechia: 'CZ',
    Denmark: 'DK',
    Djibouti: 'DJ',
    Dominica: 'DM',
    'Dominican Republic': 'DO',
    Ecuador: 'EC',
    Egypt: 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    Eritrea: 'ER',
    Estonia: 'EE',
    Eswatini: 'SZ',
    Ethiopia: 'ET',
    'Falkland Islands (Malvinas)': 'FK',
    'Faroe Islands': 'FO',
    Fiji: 'FJ',
    Finland: 'FI',
    France: 'FR',
    'French Guiana': 'GF',
    'French Polynesia': 'PF',
    'French Southern Territories': 'TF',
    Gabon: 'GA',
    Gambia: 'GM',
    Georgia: 'GE',
    Germany: 'DE',
    Ghana: 'GH',
    Gibraltar: 'GI',
    Greece: 'GR',
    Greenland: 'GL',
    Grenada: 'GD',
    Guadeloupe: 'GP',
    Guam: 'GU',
    Guatemala: 'GT',
    Guernsey: 'GG',
    Guinea: 'GN',
    'Guinea-Bissau': 'GW',
    Guyana: 'GY',
    Haiti: 'HT',
    'Heard Island and McDonald Islands': 'HM',
    'Holy See': 'VA',
    Honduras: 'HN',
    'Hong Kong,China': 'HK',
    Hungary: 'HU',
    Iceland: 'IS',
    India: 'IN',
    Indonesia: 'ID',
    Iraq: 'IQ',
    Ireland: 'IE',
    'Isle of Man': 'IM',
    Israel: 'IL',
    Italy: 'IT',
    Jamaica: 'JM',
    Japan: 'JP',
    Jersey: 'JE',
    Jordan: 'JO',
    Kazakhstan: 'KZ',
    Kenya: 'KE',
    Kiribati: 'KI',
    'Korea (Republic of)': 'KR',
    Kuwait: 'KW',
    Kyrgyzstan: 'KG',
    'Lao People\'s Democratic Republic': 'LA',
    Latvia: 'LV',
    Lebanon: 'LB',
    Lesotho: 'LS',
    Liberia: 'LR',
    Libya: 'LY',
    Liechtenstein: 'LI',
    Lithuania: 'LT',
    Luxembourg: 'LU',
    Macao: 'MO',
    Madagascar: 'MG',
    Malawi: 'MW',
    Malaysia: 'MY',
    Maldives: 'MV',
    Mali: 'ML',
    Malta: 'MT',
    MarshallIslands: 'MH',
    Martinique: 'MQ',
    Mauritania: 'MR',
    Mauritius: 'MU',
    Mayotte: 'YT',
    Mexico: 'MX',
    'Micronesia (Federated States of)': 'FM',
    'Moldova (Republic of)': 'MD',
    Monaco: 'MC',
    Mongolia: 'MN',
    Montenegro: 'ME',
    Montserrat: 'MS',
    Morocco: 'MA',
    Mozambique: 'MZ',
    'Myanmar': 'MM',
    Namibia: 'NA',
    Nauru: 'NR',
    Nepal: 'NP',
    Netherlands: 'NL',
    'New Caledonia': 'NC',
    'New Zealand': 'NZ',
    Nicaragua: 'NI',
    Niger: 'NE',
    Nigeria: 'NG',
    'Niue': 'NU',
    'Norfolk Island': 'NF',
    'North Macedonia': 'MK',
    'Northern Mariana Islands': 'MP',
    Norway: 'NO',
    Oman: 'OM',
    Pakistan: 'PK',
    Palau: 'PW',
    'Palestine, State of': 'PS',
    Panama: 'PA',
    'Papua New Guinea': 'PG',
    Paraguay: 'PY',
    Peru: 'PE',
    Philippines: 'PH',
    Pitcairn: 'PN',
    Poland: 'PL',
    Portugal: 'PT',
    'Puerto Rico': 'PR',
    Qatar: 'QA',
    Romania: 'RO',
    Russia: 'RU',
    Rwanda: 'RW',
    'Saint Barthélemy': 'BL',
    'Saint Helena, Ascension and Tristan da Cunha': 'SH',
    'Saint Kitts and Nevis': 'KN',
    'Saint Lucia': 'LC',
    'Saint Martin (French part)': 'MF',
    'Saint Pierre and Miquelon': 'PM',
    'Saint Vincent and the Grenadines': 'VC',
    'Samoa': 'WS',
    'San Marino': 'SM',
    'Sao Tome and Principe': 'ST',
    'Saudi Arabia': 'SA',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapore': 'SG',
    'Sint Maarten (Dutch part)': 'SX',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Solomon Islands': 'SB',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'South Georgia and the South Sandwich Islands': 'GS',
    'South Sudan': 'SS',
    'Spain': 'ES',
    'Sri Lanka': 'LK',
    'Suriname': 'SR',
    'Svalbard and Jan Mayen': 'SJ',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Taiwan, Province of China': 'TW',
    'Tajikistan': 'TJ',
    'Tanzania, United Republic of': 'TZ',
    'Thailand': 'TH',
    'Timor-Leste': 'TL',
    'Togo': 'TG',
    'Tokelau': 'TK',
    'Tonga': 'TO',
    'Trinidad and Tobago': 'TT',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Turkmenistan': 'TM',
    'Turks and Caicos Islands': 'TC',
    'Tuvalu': 'TV',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom of Great Britain and Northern Ireland': 'GB',
    'United States Minor Outlying Islands': 'UM',
    'United States of America': 'US',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Vanuatu': 'VU',
    'Venezuela (Bolivarian Republic of)': 'VE',
    'Viet Nam': 'VN',
    'Virgin Islands (British)': 'VG',
    'Virgin Islands (U.S.)': 'VI',
    'Wallis and Futuna': 'WF',
    'Western Sahara': 'EH',
    'Yemen': 'YE',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
};
